USE [Teste]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[P_VALOR_TOTAL_IMP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT CFOP, SUM(BASEICMS) AS VT_BASE_ICMS, SUM(VALORICMS) AS VT_ICMS, SUM(BASEIPI) AS VT_BASE_IPI, SUM(VALORIPI) AS VT_IPI 
	FROM NOTAFISCALITEM 
	GROUP BY CFOP;
END
